version: '3.5'
services:
  h5ai:
    image: awesometic/h5ai:latest
    container_name: h5ai
    restart: always
    environment:
      - PUID=$UID
      - PGID=$GID
      - TZ=Europe/Berlin
    ports:
      - "8080:80"
    volumes:
      - /volume1/docker/h5ai/shared/dir:/h5ai
      - /volume1/docker/h5ai/config/dir:/config
