version: '3.0'

volumes:
  etc_pihole-unbound:
  etc_pihole_dnsmasq-unbound:

services:
  pihole:
    container_name: pihole
    image: pluim003/pihole-unbound:latest
    hostname: pihole
    domainname: pihole.local
    ports:
      - 443:443/tcp
      - 53:53/tcp
      - 53:53/udp
      - 8080:80/tcp #Allows use of different port to access pihole web interface when other docker containers use port 80
      # - 5335:5335/tcp # Uncomment to enable unbound access on local server
      # - 22/tcp # Uncomment to enable SSH
    environment:
      - FTLCONF_LOCAL_IPV4=192.168.178.15
      - TZ=Europe/Berlin
      - WEBPASSWORD=YOURPASSWORD
      - WEBTHEME=default-light
      - REV_SERVER=true
      - REV_SERVER_TARGET=192.168.178.1
      - REV_SERVER_DOMAIN=local
      - REV_SERVER_CIDR=192.168.0.0/16
      - PIHOLE_DNS_=127.0.0.1#5335
      - DNSSEC="true"
      - DNSMASQ_LISTENING=single
    volumes:
      - etc_pihole-unbound:/etc/pihole:rw
      - etc_pihole_dnsmasq-unbound:/etc/dnsmasq.d:rw
    restart: unless-stopped
