version: "3.8"
services:
  breitband-desktop:
    image: breitband:latest
    build: https://github.com/fabianbees/breitbandmessung-docker.git
    container_name: breitband-desktop
    environment:
      - TZ=Europe/Berlin
    volumes:
      - /volume1/docker/breitbandmessung/data:/config/xdg/config/Breitbandmessung
    ports:
      - 5800:5800
    restart: unless-stopped
