version: '3.8'
services:
  breitband-desktop:
    image: breitband:latest
    container_name: breitband-desktop
    ports:
      - "5800:5800"
    volumes:
      - "$PWD/breitbandmessung/data:/config/xdg/config/Breitbandmessung"
    environment:
      - TZ=Europe/Berlin
    restart: always
